

<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">Sidebar Page
  <small>Subheading</small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="index.html">Home</a>
  </li>
  <li class="breadcrumb-item active">About</li>
</ol>

<!-- Content Row -->
<div class="row">
  <!-- Sidebar Column -->
  <div class="col-lg-3 mb-4">
    <div class="list-group">
      <a href="index.html" class="list-group-item">Home</a>
      <a href="about.html" class="list-group-item">About</a>
      <a href="services.html" class="list-group-item">Services</a>
      <a href="contact.html" class="list-group-item">Contact</a>
      <a href="portfolio-1-col.html" class="list-group-item">1 Column Portfolio</a>
      <a href="portfolio-2-col.html" class="list-group-item">2 Column Portfolio</a>
      <a href="portfolio-3-col.html" class="list-group-item">3 Column Portfolio</a>
      <a href="portfolio-4-col.html" class="list-group-item">4 Column Portfolio</a>
      <a href="portfolio-item.html" class="list-group-item">Single Portfolio Item</a>
      <a href="blog-home-1.html" class="list-group-item">Blog Home 1</a>
      <a href="blog-home-2.html" class="list-group-item">Blog Home 2</a>
      <a href="blog-post.html" class="list-group-item">Blog Post</a>
      <a href="full-width.html" class="list-group-item">Full Width Page</a>
      <a href="sidebar.html" class="list-group-item active">Sidebar Page</a>
      <a href="faq.html" class="list-group-item">FAQ</a>
      <a href="404.html" class="list-group-item">404</a>
      <a href="pricing.html" class="list-group-item">Pricing Table</a>
    </div>
  </div>
  <!-- Content Column -->
  <div class="col-lg-9 mb-4">
    <h2>Section Heading</h2>
    <div id="loadingMessage">🎥 Unable to access video stream (please make sure you have a webcam enabled)</div>
  <canvas id="canvas" hidden></canvas>
  <div id="output" hidden>
    <div id="outputMessage">No QR code detected.</div>
    <div hidden><b>Data:</b> <span id="outputData"></span></div>
  </div>

  <script src="/vendor/jsQR-master/dist/jsQR.js"></script>
  <script>
    var video = document.createElement("video");
    var canvasElement = document.getElementById("canvas");
    var canvas = canvasElement.getContext("2d");
    var loadingMessage = document.getElementById("loadingMessage");
    var outputContainer = document.getElementById("output");
    var outputMessage = document.getElementById("outputMessage");
    var outputData = document.getElementById("outputData");

    function drawLine(begin, end, color) {
      canvas.beginPath();
      canvas.moveTo(begin.x, begin.y);
      canvas.lineTo(end.x, end.y);
      canvas.lineWidth = 4;
      canvas.strokeStyle = color;
      canvas.stroke();
    }

    // Use facingMode: environment to attemt to get the front camera on phones
    navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }).then(function(stream) {
      video.srcObject = stream;
      video.setAttribute("playsinline", true); // required to tell iOS safari we don't want fullscreen
      video.play();
      requestAnimationFrame(tick);
    });

    function tick() {
      loadingMessage.innerText = "⌛ Loading video..."
      if (video.readyState === video.HAVE_ENOUGH_DATA) {
        loadingMessage.hidden = true;
        canvasElement.hidden = false;
        outputContainer.hidden = false;

        canvasElement.height = video.videoHeight;
        canvasElement.width = video.videoWidth;
        canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);
        var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
        var code = jsQR(imageData.data, imageData.width, imageData.height, {
          inversionAttempts: "dontInvert",
        });
        if (code) {
          alert(code.data);
          drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
          drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
          drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
          drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");
          outputMessage.hidden = true;
          outputData.parentElement.hidden = false;
          outputData.innerText = code.data;
        } else {
          outputMessage.hidden = false;
          outputData.parentElement.hidden = true;
        }
      }
      requestAnimationFrame(tick);
    }
  </script>
  </div>
</div>
<!-- /.row -->
